"""
Shared pytest fixtures: an isolated in-memory SQLite database per test,
using the app's real async engine/session machinery (see
app/database.py) so service-layer tests exercise the exact same query
style production code does.
"""

import pytest_asyncio
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.database import Base
from app.models import User
from app.services import (
    image_generation_service,
    ollama_ps_poller,
    reply_cross_instance_service,
    reply_generation_service,
    reply_termination_service,
    retention_poller,
    system_metrics_poller,
)
from app.services.auth_service import hash_password


@pytest_asyncio.fixture
async def db(monkeypatch) -> AsyncSession:
    """A fresh in-memory SQLite database for a single test — created
    from scratch and torn down afterwards, so tests never share state or
    depend on run order.

    Every conversation's reply is now generated by a fully detached
    background task (see app.services.reply_generation_service) that
    opens its own AsyncSessionLocal() rather than reusing the request's
    (here, the test's own `db`) session — by default that would be the
    app's real database, not this test's isolated one. Pointing it at a
    session factory bound to this same in-memory engine is what lets a
    test that drains build_reply_stream to completion see the background
    task's writes through this same `db` fixture, with no per-test
    wiring needed. A test that needs to simulate a *second*, later
    session (e.g. after this one is gone) still builds its own separate
    engine, same as before — this only covers the common case of
    "finish generating and read the result back." Patched in
    reply_termination_service and reply_cross_instance_service too (not
    just reply_generation_service): `from app.database import
    AsyncSessionLocal` binds an independent name in *each* module's own
    namespace, so patching one module's copy never affects another's —
    both handle their own piece of a cancelled/cross-instance-deleted
    reply (split out of reply_generation_service, see that module's own
    docstring). image_generation_service gets the same treatment for the
    same reason — its own background job task also opens a fresh
    AsyncSessionLocal() rather than reusing this fixture's session, and
    so do ollama_ps_poller (its periodic /api/ps poll),
    system_metrics_poller (its periodic CPU/RAM/disk sample), and
    retention_poller (its periodic prune of both, plus telemetry_events).
    """
    engine = create_async_engine("sqlite+aiosqlite:///:memory:")
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    session_factory = async_sessionmaker(engine, expire_on_commit=False)
    monkeypatch.setattr(reply_generation_service, "AsyncSessionLocal", session_factory)
    monkeypatch.setattr(reply_termination_service, "AsyncSessionLocal", session_factory)
    monkeypatch.setattr(reply_cross_instance_service, "AsyncSessionLocal", session_factory)
    monkeypatch.setattr(image_generation_service, "AsyncSessionLocal", session_factory)
    monkeypatch.setattr(ollama_ps_poller, "AsyncSessionLocal", session_factory)
    monkeypatch.setattr(system_metrics_poller, "AsyncSessionLocal", session_factory)
    monkeypatch.setattr(retention_poller, "AsyncSessionLocal", session_factory)
    async with session_factory() as session:
        yield session

    await engine.dispose()


@pytest_asyncio.fixture
async def user(db: AsyncSession) -> User:
    """A single ordinary (non-admin) user, persisted, for tests that
    need a real owner_id to attach rows to."""
    u = User(username="alice", password_hash=hash_password("alice-pw"), role="user")
    db.add(u)
    await db.commit()
    await db.refresh(u)
    return u


@pytest_asyncio.fixture
async def admin_user(db: AsyncSession) -> User:
    u = User(username="admin", password_hash=hash_password("admin-pw"), role="admin")
    db.add(u)
    await db.commit()
    await db.refresh(u)
    return u


@pytest_asyncio.fixture
async def channel_manager_user(db: AsyncSession) -> User:
    """A user holding the "channel_manager" role — eligible to be
    flagged as a manager on a specific channel (see
    app/services/channel_service.py). Holding this role alone grants no
    rights on any given channel; it only makes the user a valid pick for
    that channel's manager_user_ids."""
    u = User(username="carol", password_hash=hash_password("carol-pw"), role="channel_manager")
    db.add(u)
    await db.commit()
    await db.refresh(u)
    return u
