"""
Pydantic schemas: define the shape of JSON that flows in and out of the
API. Split one domain per file (see CLAUDE.md's file-size rule) instead
of one large schemas.py, and re-exported here so the rest of the app
keeps writing `from app.schemas import ChatRequest, ...` exactly as
before — this package boundary is an internal reorganization, not a
change to any call site outside it.
"""

from app.schemas.channel import ChannelCreate, ChannelMemberOut, ChannelOut, ChannelSummary, ChannelUpdate
from app.schemas.chat import DeleteMessageResponse, MessageOut, MessagesLatestResponse
from app.schemas.comfyui_config import ComfyUIProcessConfig, ComfyUIStatus
from app.schemas.common import (
    ActiveEngineConfig,
    AvailableVersions,
    EngineName,
    GenerationParams,
    HostHealthCheck,
    InstallDefaults,
    OkResponse,
    PinType,
)
from app.schemas.conversation import ConversationCreate, ConversationOut, ConversationUpdate
from app.schemas.db_config import (
    DbActionResult,
    DbConfig,
    DbConfigUpdate,
    InternalSwitchDatabaseRequest,
    MysqlParams,
    SqliteParams,
)
from app.schemas.document import (
    DocumentOut,
    KnowledgeSummary,
    RagLimits,
    ScopeSummary,
    UploadJobStatus,
    UploadResult,
)
from app.schemas.health import HealthStatus
from app.schemas.http_proxy_config import HttpProxyConfig
from app.schemas.image_generation import CheckpointList, ImageGenerationJobOut, ImageGenerationRequest
from app.schemas.instances import InstancesConfig, InstanceStatus, InstancesUpdate, ProxyMode
from app.schemas.matricxon_server_config import (
    MatricxonAutoDetectedPath,
    MatricxonServerConfig,
    MatricxonServerStatus,
)
from app.schemas.model_catalog import (
    AddExtendedModelRequest,
    CatalogEntry,
    DeleteModelResponse,
    EmbeddingCatalogEntry,
    EmbeddingModelCatalogResponse,
    ExtendedModelCatalogResponse,
    HfFileOption,
    HfRepoFilesRequest,
    HfRepoFilesResponse,
    HfSearchResult,
    HideModelRequest,
    HideModelResponse,
    InstalledModelsResponse,
    ModelCatalogResponse,
    PullModelRequest,
    RemoveExtendedModelRequest,
    SearchHfModelsRequest,
    SearchHfModelsResponse,
)
from app.schemas.note import (
    NoteCreate,
    NoteOut,
    NotePinCreate,
    NotePinOut,
    NoteSlotOut,
    NoteSlotUpdate,
    NoteUpdate,
)
from app.schemas.ollama_server_config import OllamaAutoDetectedPath, OllamaServerConfig, OllamaServerStatus
from app.schemas.settings import (
    ChannelDeliveryMode,
    DefaultModel,
    HardwareSummary,
    RagAvailability,
    ReplyTimeout,
    RetentionSettings,
    SystemInfo,
    TitleMode,
    UiTheme,
)
from app.schemas.stats import (
    ConversationStats,
    CountByKey,
    KnowledgeBaseStats,
    LiveConversationStats,
    MessageStats,
    StatsSummary,
    UserStats,
)
from app.schemas.system_metrics import GpuHistoryPoint, GpuStat, SystemMetricPoint, SystemMetricsSummary
from app.schemas.telemetry import (
    HostStats,
    LatencyTimeBucket,
    LoadedModelSnapshot,
    ModelLatencyStats,
    OllamaTelemetrySummary,
)
from app.schemas.user import (
    AccountProfileOut,
    AccountProfileUpdate,
    ChangePasswordRequest,
    PublicProfileOut,
    UserCreate,
    UserOut,
    UserUpdate,
)

__all__ = [
    "ChannelCreate",
    "ChannelMemberOut",
    "ChannelOut",
    "ChannelSummary",
    "ChannelUpdate",
    "DeleteMessageResponse",
    "MessageOut",
    "MessagesLatestResponse",
    "ComfyUIProcessConfig",
    "ComfyUIStatus",
    "ActiveEngineConfig",
    "AvailableVersions",
    "EngineName",
    "GenerationParams",
    "HostHealthCheck",
    "InstallDefaults",
    "OkResponse",
    "PinType",
    "ConversationCreate",
    "ConversationOut",
    "ConversationUpdate",
    "DbActionResult",
    "DbConfig",
    "DbConfigUpdate",
    "InternalSwitchDatabaseRequest",
    "MysqlParams",
    "SqliteParams",
    "DocumentOut",
    "KnowledgeSummary",
    "RagLimits",
    "ScopeSummary",
    "UploadJobStatus",
    "UploadResult",
    "HealthStatus",
    "HttpProxyConfig",
    "CheckpointList",
    "ImageGenerationJobOut",
    "ImageGenerationRequest",
    "InstanceStatus",
    "InstancesConfig",
    "InstancesUpdate",
    "ProxyMode",
    "NoteCreate",
    "NoteOut",
    "NotePinCreate",
    "NotePinOut",
    "NoteSlotOut",
    "NoteSlotUpdate",
    "NoteUpdate",
    "MatricxonAutoDetectedPath",
    "MatricxonServerConfig",
    "MatricxonServerStatus",
    "OllamaAutoDetectedPath",
    "OllamaServerConfig",
    "OllamaServerStatus",
    "AddExtendedModelRequest",
    "CatalogEntry",
    "DeleteModelResponse",
    "EmbeddingCatalogEntry",
    "EmbeddingModelCatalogResponse",
    "ExtendedModelCatalogResponse",
    "HfFileOption",
    "HfRepoFilesRequest",
    "HfRepoFilesResponse",
    "HfSearchResult",
    "HideModelRequest",
    "HideModelResponse",
    "InstalledModelsResponse",
    "ModelCatalogResponse",
    "PullModelRequest",
    "RemoveExtendedModelRequest",
    "SearchHfModelsRequest",
    "SearchHfModelsResponse",
    "ChannelDeliveryMode",
    "DefaultModel",
    "HardwareSummary",
    "RagAvailability",
    "ReplyTimeout",
    "RetentionSettings",
    "SystemInfo",
    "TitleMode",
    "UiTheme",
    "ConversationStats",
    "CountByKey",
    "KnowledgeBaseStats",
    "LiveConversationStats",
    "MessageStats",
    "StatsSummary",
    "UserStats",
    "GpuHistoryPoint",
    "GpuStat",
    "SystemMetricPoint",
    "SystemMetricsSummary",
    "HostStats",
    "LatencyTimeBucket",
    "LoadedModelSnapshot",
    "ModelLatencyStats",
    "OllamaTelemetrySummary",
    "AccountProfileOut",
    "AccountProfileUpdate",
    "ChangePasswordRequest",
    "PublicProfileOut",
    "UserCreate",
    "UserOut",
    "UserUpdate",
]
